name: Build CV
on:
  pull_request:
    branches:
      - master

jobs:
  create-cvs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install RenderCV
        run: |
          python -m pip install --upgrade pip
          pip install "rendercv[full]"

      - name: Verify RenderCV installation
        run: |
          rendercv --version

      - name: Get Changed Files
        uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          # Specify the path to the folder you want to check
          files: "data/*.yaml"

      - name: Generate profiles
        continue-on-error: false
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "Processing $file"
              ./generate_profile.sh "$file"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[create-cv-bot]"
          git config --global user.email "github-actions[create-cv-bot]@users.noreply.github.com"
          git add profiles/*.pdf
          git commit -m "Updated pdf profiles for changed YAML files"
          git push origin $(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
